name: åŠŸèƒ½å»ºè®®
description: å°åº¦è®¾å¤‡ï¼Œè¯¥æ’ä»¶æ²¡æœ‰åŒæ­¥è®¾å¤‡ / å®žä½“åŠŸèƒ½å»ºè®® / æ’ä»¶åŠŸèƒ½å»ºè®®
body:
  - type: input
    validations:
      required: true
    attributes:
      label: Device model / è®¾å¤‡åž‹å·
      placeholder: éœ€è¦æä¾›å»ºè®®çš„è®¾å¤‡åž‹å·ï¼Œæ²¡æœ‰å¡«å†™æ— 
      description: |
        > [âš™ï¸ å°åº¦ç½‘é¡µç‰ˆ > æœ‰é—®é¢˜çš„è®¾å¤‡ > äº§å“/å…¬å¸/è®¾å¤‡å](https://xiaodu.baidu.com/saiya/smarthome/index.html)

  - type: input
    attributes:
      label: Component version / æ’ä»¶ç‰ˆæœ¬
      placeholder: 0.7.x
      description: |
        > [âš™ï¸ Settings > System > Repairs > Three Dots in Upper Right > System information](https://my.home-assistant.io/redirect/system_health) > `hass_xiaodu`
        > [âš™ï¸ é…ç½® > ç³»ç»Ÿ > ä¿®å¤ > å³ä¸Šè§’ä¸‰ä¸ªç‚¹ > ç³»ç»Ÿä¿¡æ¯](https://my.home-assistant.io/redirect/system_health) > `hass_xiaodu`

  - type: input
    attributes:
      label: HA core version / HAç‰ˆæœ¬
      placeholder: 2024.x.x
      description: |
        > [âš™ï¸ Settings > â„¹ï¸ï¸ About](https://my.home-assistant.io/redirect/info)
        > [âš™ï¸ é…ç½® > â„¹ï¸ï¸ å…³äºŽ](https://my.home-assistant.io/redirect/info)

  - type: textarea
    attributes:
      label: The problem / åŠŸèƒ½å»ºè®®æå†™

  - type: textarea
    validations:
      required: true
    attributes:
      label: Entity attributes / å®žä½“å±žæ€§
      render: yaml
      description: |
        > [ðŸ”¨ Developer tools > â„¹ï¸ State](https://my.home-assistant.io/redirect/developer_states) > ðŸ” Filter (`button.xxxx_info`)
        > [ðŸ”¨ å¼€å‘è€…å·¥å…· > â„¹ï¸ çŠ¶æ€](https://my.home-assistant.io/redirect/developer_states) > ðŸ” ç­›é€‰è¯¥è®¾å¤‡ä¸‹çš„infoå®žä½“
        > å¦‚æžœæ²¡æœ‰å®žä½“ï¼Œè¯·å¡«å†™`æ— å®žä½“`
